### ISSUE TITLE
点击放大的图片隐藏时，隐藏的效果有点体验性问题

### ISSUE THREAD

**Issue by fhefh2015** [CoderXLLau/XLPhotoBrowser#1]
在BaseTestViewController，我将self.scrollView.xl_y的值修改成了 -10;

点击放大的图片隐藏时，隐藏的效果有点体验性问题

![untitled](https://cloud.githubusercontent.com/assets/14891797/17502701/ad61c532-5e1c-11e6-8a7c-aec15817cea4.gif)

**Comment by CoderXLLau** [comment]
导航条遮住了部分图片,最后消失的时候就是这个效果,如果你有更好的方案,欢迎你再反馈
