### ISSUE TITLE
报错后，不能滑动

### ISSUE THREAD

**Issue by MJHee** [CoderXLLau/XLPhotoBrowser#4]
报出下面错误后，tableView不能滑动，图片不能点击：
===========================
===========================
=== XLPhotoBrowser' Log ===
提示信息:需要提供源视图才能做弹出/退出图片浏览器的缩放动画
所在方法:-[XLPhotoBrowser showFirstImage]
所在行数:752
===========================
===========================

**Comment by CoderXLLau** [comment]
可以提供更详细的信息嘛?
你可以查看一下视图层次结构,是否存在透明遮罩视图

**Comment by CoderXLLau** [comment]
看下是否是报错导致程序崩溃?
