### ISSUE TITLE
楼主 如果我想添加朋友圈的新交互 向下拖动图片关闭预览 同iOS照片功能该怎么写呢

### ISSUE THREAD

**Issue by 1271918333** [CoderXLLau/XLPhotoBrowser#5]

**Comment by CoderXLLau** [comment]
添加一个Pan手势，监听向下滑动，处理对应的逻辑，具体的你可以先试一下，下个版本我尝试把这个功能加进去！

**Comment by 1271918333** [comment]
我试了，但是会影响左右滑动。能不能让我看看具体是怎么实现的，谢谢


发自网易邮箱大师
在2017年03月21日 09:32，github共享库验证 写道：

添加一个Pan手势，监听向下滑动，处理对应的逻辑，具体的你可以先试一下，下个版本我尝试把这个功能加进去！

**Comment by CoderXLLau** [comment]
我还没做这个功能，你可以在我源码的基础上兼容一下，肯定要考虑其他事件的处理，多想想办法！

**Comment by 1271918333** [comment]
发自网易邮箱大师
在2017年03月21日 10:35，github共享库验证 写道：

我还没做这个功能，你可以在我源码的基础上兼容一下，肯定要考虑其他事件的处理，多想想办法！

**Comment by 1271918333** [comment]
我想了挺多办法的但是都有点小问题。我想我还是看看你怎么实现的吧。

**Comment by CoderXLLau** [comment]
我最近公司项目比较忙，我尽快研究一下更新版本，有问题欢迎加群详聊！

**Comment by 1271918333** [comment]
我加群了，怎么跟您联系呢，大神你什么时候能更新，我是真没辙了。而且我很急呢。😭


发自网易邮箱大师
在2017年03月22日 09:39，github共享库验证 写道：

Closed #5.

**Comment by CoderXLLau** [comment]
群主就是我，你@我就好了，我们有个新项目，最近一直比较忙，所以可能不会很快更新，而且，我也需要时间研究一下，不好意思！
