### ISSUE TITLE
建议增加一个协议，获取图片浏览滑动的实时index下标

### ISSUE THREAD

**Issue by RenSihao** [CoderXLLau/XLPhotoBrowser#6]

**Comment by CoderXLLau** [comment]
谢谢你的建议，下个版本我添加一个协议进去，方便大家使用！现在你可以通过XLPhotoBrowser头文件中的这个属性获取当前图片索引
/**
 *  当前显示的图片位置索引 , 默认是0
 */
@property (nonatomic, assign ) NSInteger currentImageIndex;

**Comment by RenSihao** [comment]
是的，我用了KVO去监听，手法比较麻烦。对了，昨天调试的时候意外发现一个小bug，在寻找当前主window的时候，我工程里引入了FLEX这个调试框架，它直接返回了FLEX这个window......当然只会在debug阶段并且没有关闭FLEX的时候才会出现这个问题，建议可以的话修复一下：）

**Comment by CoderXLLau** [comment]
对于寻找主窗口这个问题，因为我目前没有找到兼容所有工程结构的方法，我的建议是根据自己的工程结构情况，自己维护。

**Comment by RenSihao** [comment]
get !
